# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grooming', '0010_auto_20170824_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grooming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grooming.Grooming', verbose_name='Grooming')),
            ],
        ),
    ]
