# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-01 06:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grooming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Grooming')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='CreateTime')),
                ('modify_time', models.DateTimeField(auto_now_add=True, verbose_name='ModifyTime')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=' author')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='TagName')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Tagcreatetime')),
                ('modify_time', models.DateTimeField(auto_now_add=True, verbose_name='Tagmodifytime')),
            ],
            options={
                'verbose_name_plural': 'Tag',
                'ordering': ['name'],
                'verbose_name': 'Tag',
            },
        ),
        migrations.AddField(
            model_name='grooming',
            name='tags',
            field=models.ManyToManyField(blank=True, to='grooming.Tag', verbose_name='tags'),
        ),
    ]
