# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 00:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grooming', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grooming',
            old_name='modify_time',
            new_name='last_modified_time',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='modify_time',
            new_name='last_modified_time',
        ),
    ]
