# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-04 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooming', '0002_auto_20161103_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name=b'Index Content')),
            ],
        ),
    ]
