# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-04 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooming', '0003_indexedit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexedit',
            name='content',
            field=models.CharField(max_length=500, verbose_name=b'Index Content'),
        ),
    ]
