# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooming', '0004_auto_20161104_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexedit',
            name='content',
            field=models.TextField(verbose_name='Index Content'),
        ),
    ]
