# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grooming', '0005_auto_20161104_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grooming',
            name='author',
        ),
        migrations.RemoveField(
            model_name='grooming',
            name='tags',
        ),
    ]
