# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooming', '0006_auto_20161107_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='grooming',
            name='assumption',
            field=models.TextField(null=True, verbose_name='Assumption'),
        ),
        migrations.AddField(
            model_name='grooming',
            name='question',
            field=models.TextField(null=True, verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='grooming',
            name='scope',
            field=models.TextField(null=True, verbose_name='Scope'),
        ),
        migrations.AddField(
            model_name='grooming',
            name='sprint',
            field=models.CharField(max_length=200, null=True, verbose_name='Sprint'),
        ),
        migrations.AlterField(
            model_name='grooming',
            name='content',
            field=models.TextField(null=True, verbose_name='Grooming'),
        ),
    ]
