# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooming', '0007_auto_20161109_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grooming',
            name='assumption',
            field=models.TextField(default='No Assumption', verbose_name='Assumption'),
        ),
        migrations.AlterField(
            model_name='grooming',
            name='content',
            field=models.TextField(default='No Case Need', verbose_name='ATDD Case'),
        ),
        migrations.AlterField(
            model_name='grooming',
            name='question',
            field=models.TextField(default='No Question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='grooming',
            name='scope',
            field=models.TextField(default='Please Describe The Scope Here', verbose_name='Scope'),
        ),
    ]
