# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 09:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grooming', '0009_auto_20161110_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATDDCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suitename', models.TextField(default='', verbose_name='Suitename')),
                ('testname', models.TextField(default='', verbose_name='Testname')),
                ('precondition', models.TextField(default='', verbose_name='Precondition')),
                ('operation', models.TextField(default='', verbose_name='Operation')),
                ('expectresult', models.TextField(default='', verbose_name='Expect Result')),
                ('checkpoint', models.TextField(default='', verbose_name='Check Point')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='FeatureName')),
                ('content', models.TextField(default='', verbose_name='FeatureContent')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='FeatureCreateTime')),
                ('last_modified_time', models.DateTimeField(auto_now_add=True, verbose_name='FeatureLastModify')),
                ('time_box', models.FloatField(default=0, verbose_name='FeatureTimeBox')),
                ('material', models.FileField(upload_to='Features/%Y/%m/%d/', verbose_name='FeatureMaterial')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=' FeatureAuthor')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='ItemName')),
                ('content', models.TextField(default='', verbose_name='ItemContent')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='ItemCreateTime')),
                ('last_modified_time', models.DateTimeField(auto_now_add=True, verbose_name='ItemLastModify')),
                ('time_box', models.FloatField(default=0, verbose_name='ItemTimeBox')),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grooming.Feature', verbose_name='Feature')),
            ],
        ),
        migrations.DeleteModel(
            name='IndexEdit',
        ),
        migrations.AddField(
            model_name='grooming',
            name='attend_person',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='AttednPerson'),
        ),
        migrations.AddField(
            model_name='grooming',
            name='case_file',
            field=models.FilePathField(default='', verbose_name='CaseFile'),
        ),
        migrations.AddField(
            model_name='grooming',
            name='iv_cost_time',
            field=models.FloatField(default=0, verbose_name='I&VCostTime'),
        ),
        migrations.AddField(
            model_name='grooming',
            name='sw_cost_time',
            field=models.FloatField(default=0, verbose_name='SWCostTime'),
        ),
        migrations.AlterField(
            model_name='grooming',
            name='assumption',
            field=models.TextField(default='', verbose_name='Assumption'),
        ),
        migrations.AlterField(
            model_name='grooming',
            name='content',
            field=models.TextField(default='', verbose_name='ATDD Case'),
        ),
        migrations.AlterField(
            model_name='grooming',
            name='question',
            field=models.TextField(default='', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='grooming',
            name='scope',
            field=models.TextField(default='', verbose_name='Scope'),
        ),
        migrations.AlterField(
            model_name='grooming',
            name='sprint',
            field=models.CharField(default='Sprint-', max_length=200, verbose_name='Sprint'),
        ),
        migrations.AddField(
            model_name='atddcase',
            name='grooming_belong_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grooming.Grooming'),
        ),
        migrations.AddField(
            model_name='grooming',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grooming.Item', verbose_name='Item'),
        ),
    ]
