# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grooming', '0010_auto_20170824_1724'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.RemoveField(
            model_name='atddcase',
            name='checkpoint',
        ),
        migrations.RemoveField(
            model_name='atddcase',
            name='expectresult',
        ),
        migrations.RemoveField(
            model_name='atddcase',
            name='grooming_belong_to',
        ),
        migrations.RemoveField(
            model_name='atddcase',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='atddcase',
            name='precondition',
        ),
        migrations.RemoveField(
            model_name='atddcase',
            name='testname',
        ),
        migrations.RemoveField(
            model_name='grooming',
            name='case_file',
        ),
        migrations.RemoveField(
            model_name='grooming',
            name='content',
        ),
        migrations.RemoveField(
            model_name='grooming',
            name='feature',
        ),
        migrations.AddField(
            model_name='atddcase',
            name='case_content',
            field=models.TextField(default='', verbose_name='CaseContent'),
        ),
        migrations.AddField(
            model_name='atddcase',
            name='case_file',
            field=models.FilePathField(default='', verbose_name='CaseFile'),
        ),
        migrations.AddField(
            model_name='atddcase',
            name='grooming',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grooming.Grooming', verbose_name='Grooming'),
        ),
        migrations.AddField(
            model_name='grooming',
            name='phase',
            field=models.IntegerField(default=1, verbose_name='GroomingPhase'),
        ),
        migrations.AlterField(
            model_name='atddcase',
            name='suitename',
            field=models.TextField(default='', max_length=200, verbose_name='Suitename'),
        ),
    ]
